// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ZNpfz6IOWypy7zYZDTQT9ZbMID5xL1w',
    appId: '1:927483086196:web:d431b98459d97e803ad821',
    messagingSenderId: '927483086196',
    projectId: 'sankar-group-cb122',
    authDomain: 'sankar-group-cb122.firebaseapp.com',
    storageBucket: 'sankar-group-cb122.firebasestorage.app',
    measurementId: 'G-YGPZSDNHFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0n-D2R6mHJNFFxTFZUSo0kwAI60zd7Q',
    appId: '1:927483086196:android:8160a11c28cba8b93ad821',
    messagingSenderId: '927483086196',
    projectId: 'sankar-group-cb122',
    storageBucket: 'sankar-group-cb122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLmQRoD1k0qJqeEFzMHgZ8ptkLcMiriPM',
    appId: '1:927483086196:ios:b2be6471fa484dfd3ad821',
    messagingSenderId: '927483086196',
    projectId: 'sankar-group-cb122',
    storageBucket: 'sankar-group-cb122.firebasestorage.app',
    iosBundleId: 'com.example.assignmentSankarGroup',
  );
}
